### ISSUE TITLE
Need a JSON schema for the Registry v2 API

### ISSUE THREAD

**Issue by grexe** [distribution/distribution#1060]
In addition to the [Docker registry v2 API spec](http://docs.docker.com/registry/spec/api), a formal [JSON schema definition](http://json-schema.org/) would be needed to allow for easy, correct and reproducable (i.e. auto-generatable) client development.

Currently, e.g. as a Java developer, I have to issue sample requests according to the spec and feed the JSON output to my code generator of choice to get my mapper objects, which is suboptimal.

**Comment by stevvooe** [comment]
@grexe It is available [here](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md). If you would like it to be done in a specific format, you're welcome to provide a PR.

**Comment by stevvooe** [comment]
@cliffbdf Contributions are welcome. We probably won't be porting the registry API to GRPC anytime soon, as GRPC isn't yet flexible enough (tied to http/2). There are also framing issues to consider when using GRPC. Large data streams end up having to be chunked then framed into a message, creating unnecessary data copies (Go handles this fine, but other languages may not). HTTP API just streams the body. Pure client implementations end up being quite performant from a transfer perspective.

If you're having a specific problem with the API, please say so. Switching protocols isn't realistic.

**Comment by cliffbdf** [comment]
@stevvooe Yes, re. HTTP/2, but it might only be an issue of Go language support. According to the HTTP/2 web page, it does not change any of the application-level protocol semantics (headers, etc. that are used by applications): "HTTP/2 is a replacement for how HTTP is expressed “on the wire.” It is not a ground-up rewrite of the protocol; HTTP methods, status codes and semantics are the same, and it should be possible to use the same APIs as HTTP/1.x (possibly with some small additions) to represent the protocol." But this does not mean that it is available right now from the golang libraries. I have not used HTTP/2 so I cannot say. But I suggest keeping an eye on this, because gRPC is a far superior and cleaner approach, once using it becomes viable - perhaps Registry v3?

**Comment by milosgajdos** [comment]
Image Manifest schemas are managed by OCI. Please open an issue in https://github.com/opencontainers/distribution-spec
