### ISSUE TITLE
Multi-stage build

### ISSUE THREAD

**Issue by m5p3nc3r** [distribution/distribution#2250]
Hi Guys

After attending DockerCon, and being introduced to the multi-stage dockerfile build concept, I thought I would try it out on this project.  The aim would be that the image built from the project would contain just the required build artefacts and deprecate the need for the distribution-library-image project in the creation of hub official images.

My question is - I have it working, the changes are minimal, should I create a PR with what I have in full knowledge that it will currently not pass any of the validation checks because it requires new features in docker that have not yet been officially released.

Cheers

**Comment by m5p3nc3r** [comment]
Adding the Dockerfile here (please excuse the .txt, github wouldn't let me add it otherwise!)

[Dockerfile.txt](https://github.com/docker/distribution/files/945751/Dockerfile.txt)

**Comment by dmcgowan** [comment]
I would suggest opening this up as PR. However can you add the file as `Dockerfile.minimal` or something rather than replacing the main `Dockerfile` for now. The multi stage build support is only in the latest version of Docker and the main Dockerfile for this project is primarily aimed at use for development.

Note the `Dockerfile` used to create the official registry image is already minimal and can be found in this repo https://github.com/docker/distribution-library-image. This repo nails down the build process a little more by having the binary checked in, but not sure if there are plans to move official builds to multi-stage builds.

**Comment by m5p3nc3r** [comment]
Hi Derek
Thanks for the feedback.  I will create a PR and rename the file Dockerfile.minimal for now.
I do know that there is a minimal image available, however the problem is that it is X86 only.  With this dockerfile, we can start the process of having the official image build directly from source which gives us the ability to create multi-architecture images?

**Comment by m5p3nc3r** [comment]
Pull request #2254 has been created.

**Comment by m5p3nc3r** [comment]
Closing stale issue
