### ISSUE TITLE
Reference documentation and grammar seem to be inconsistent

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#2658]
https://github.com/docker/distribution/blob/master/reference/regexp.go

Example:

 * `DigestRegexp = match([A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*[:][[:xdigit:]]{32,})`

In the doc (as seen on https://docs.docker.com/registry/spec/api/):

```
digest      := algorithm ":" hex
algorithm   := /[A-Fa-f0-9_+.-]+/
hex         := /[A-Fa-f0-9]+/
```

**Comment by rahul3002** [comment]
i would like to fix this issue

**Comment by TheSwarnim** [comment]
Hi @Jamstah, I would like to work on this. But I'm not understand fully what I've to do. Can you please help me out?

**Comment by Jamstah** [comment]
It looks like the documentation used to be wrong according to the description in this issue. Looking at it now, it has already been fixed.

I think this is closable.

**Comment by TheSwarnim** [comment]
Ok, @Jamstah. Do you have any issue that I can pick as a beginner. Please let me know

**Comment by Jamstah** [comment]
There is an option here: https://github.com/distribution/distribution/issues/1793

I found that looking at this list of "help wanted": https://github.com/distribution/distribution/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

Otherwise, its a case of looking through the issues list to see if there's something that catches your attention :)

**Comment by Jamstah** [comment]
The issues list is long and needs some attention, even if all you do is find some issues that are no longer a problem, its still valuable to the project.

**Comment by milosgajdos** [comment]
Closing fixed in https://github.com/distribution/distribution/pull/3244
