### ISSUE TITLE
Repo name validation is misused

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#2668]
Regardless of your registry actual domain name, the Parse method https://github.com/docker/distribution/blob/v2.7.0/reference/reference.go#L189 is always receiving:

`docker.io/foo/bar` or `docker.io/library/foo` (where `foo/bar` or `foo` is your image).

It seems to be because we are calling https://github.com/docker/distribution/blob/v2.7.0/reference/normalize.go#L33 on `vars.name` from the context, which is apparently just the repo name (without the domain).

This makes the implementation deviate from the stated intent of the grammar.

If NameTotalLengthMax https://github.com/docker/distribution/blob/v2.7.0/reference/reference.go#L37 was meant to limit the total size of the image name including the domain, then it must use the actual registry domain (+port).

If NameTotalLengthMax should be applied just on the path component, regardless of the domain, then we should not normalize `vars.name` before validating it (this is what the `WithName` method does, by the way).

A fix for this need to be carefully thought, as in the current situation the actual restriction is on repo names at 237 characters (with single components) and 245 characters if they contain a slash regardless of the domain component - introducing proper domain name validation may render existing images invalid.

Let me know if I'm missing something here.

cc @caervs @dmcgowan @tiborvass

**Comment by DavidSpek** [comment]
@milosgajdos Any idea if this is still relevant off the top of your head?

**Comment by milosgajdos** [comment]
I believe it is. Equally, I'd love if `distribution-spec` defined these [reference] limits, but it's a major gotcha for folks unfamiliar with this.

**Comment by milosgajdos** [comment]
@thaJeztah I feel like this issue belongs to https://github.com/distribution/reference WDYT?

**Comment by milosgajdos** [comment]
Taking this out of `v3` milestone as it needs to be transferred to https://github.com/distribution/reference after the `v3` is cut.

CC: @distribution/distribution-maintainers @distribution/distribution-reviewers

**Comment by thaJeztah** [comment]
Looks like the length-check was added in https://github.com/distribution/distribution/commit/31a448a628b61bc50d4790b49c489b5747ebeca5, which was part of

- https://github.com/distribution/distribution/pull/963
- (carry of https://github.com/distribution/distribution/pull/690)

We should look indeed what the original intent was; length of the fully-qualified name, or just the path.

**Comment by milosgajdos** [comment]
> We should look indeed what the original intent was

Starting my time machine. BRB.

Maybe @dmcgowan knows? Either way this issue now belongs to the `reference` repo - or will belong there once we've cut `v3` and deprecated `v2.8.X`

**Comment by thaJeztah** [comment]
> We should look indeed what the original intent was; length of the fully-qualified name, or just the path.

Looking at the original PR before carry (https://github.com/distribution/distribution/pull/690), I see the name of the const was `RepositoryNameTotalLengthMax` https://github.com/distribution/distribution/pull/690/files#diff-cee27f18bd2d4ca82421678d3943ab6e83f082e2b9abedb9da4002fb362523b5R10-R13

Which makes me consider that domain-name is not meant to be included. That _could_ make sense if we want to restrict length, but still allow an image to be pushed to another repository, using the same "name" (I'm putting "name" in quotes here, because the fully-qualified name, including the domain/host part would be the name). Being able to push an image to a different registry would also be the case when using a registry as (pull-through) mirror; if we'd include domain-name in the length-restriction, it would potentially be impossible to host a repository from the upstream registry.

Also based on the original name (`RepositoryNameTotalLengthMax`), I will assume that `tag` is not part of this, so only the repository name ("path").

**Comment by thaJeztah** [comment]
☝️ I should add to the above;

- it's _POSSIBLE_ that the original PR was based on existing logic/handling in the docker engine at the time (https://github.com/docker/docker), so I may dig further there in case I can find more details
- That said; the PR was related to "v2" and digests (things that didn't exist before (v1)), so information from back then may still not be fully relevant
- ⚠️ while changing the logic to _exclude_ domain-name should be backward compatible with existing repository names; there may still be caveats (e.g. if a registry assumes _TOTAL_ length, and (e.g.) keeps an index with that assumption. That _could_ cause issues if (e.g.) a database-schema to store the information assumes 255 characters for the reference in total
- ☝️ so in either case, changing this should probably be called out explicitly in changelog / release notes.

**Comment by milosgajdos** [comment]
> Which makes me consider that domain-name is not meant to be included.

This is a speculation right 😄 None of this is defined by `distribution-spec` <insert sad panda emoji>
