### ISSUE TITLE
logs written to stderr, not stdout

### ISSUE THREAD

**Issue by dcj** [distribution/distribution#2855]
I built distribution v2.7.1 on FreeBSD 11.2, and ran it there also.
Redirecting stdout to a file did not work, the logs continued to be written to the terminal.
When I redirected stderr to a file, all the logs were written to that file.
I did not have this problem with v2.6.1

**Comment by thaJeztah** [comment]
Looks like this is due to an upstream change in the Logrus package; https://github.com/sirupsen/logrus/commit/f8f08842cce7ed05c296430852f60f287458c529#diff-40646a6e1108f49d452915ba3515c206 (https://github.com/sirupsen/logrus/pull/170)

@dmcgowan @manishtomar might be good to mention this change in the changelog?

**Comment by dmcgowan** [comment]
Yes, this is a documentation issue. Logs should be going to `stderr` but that should be highlighted.
