### ISSUE TITLE
Invalid region provided: eu-north-1

### ISSUE THREAD

**Issue by bwesen** [distribution/distribution#2870]
Guess same issue as all the other issues complaining about region validation.

If these regions have to be hardcoded in a list inside docker registry, isn't it time to drop that validation? Every time AWS opens a region someone needs to file an issue, a patch issued and a release done?

**Comment by blockmar** [comment]
No response in 3 months. Direct me to the code and I will make a PR.

**Comment by KlavsKlavsen** [comment]
I just checked the code.. its just because you have not rebuilt using latest github.com/aws/aws-sdk-go - as that supports that endpoint - and the you use does not.

**Comment by qvistgaard** [comment]
What is the status of this issue. i just checked it still doesn't work in 2.7.1

**Comment by jasdel** [comment]
Looks like this issue is triggered by the behavior of the [S3 storage driver](https://github.com/docker/distribution/blob/244d5246c2f193d50b2f8fd220784958a5e1318b/registry/storage/driver/s3-aws/s3.go#L108-L114)'s query of the SDK's know regions. There are two issues with this, the version of the SDK pinned in go.mod is fairly old, which leads to regions released after the SDK version is published not being identified as valid regions.

Updating the pinned version of the SDK will improve this, but you'll be chasing the SDK versions as new regions are added.

I suggest a change to this logic to remove querying the SDK for the set of valid regions, if possible. If the set of valid regions are required you could explicitly include a set of regions in the toolset, or use [Ec2's DescribeRegions](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeRegions) API call to the most recent set of  regions dynamically at runtime.

**Comment by bwesen** [comment]
In case someone needs it, the workaround is to bypass this check by explicitly specifying the endpoint in the environment variables (it can't be done in the config.yml itself but do it in the docker-compose.yml in case you use compose to run this for example):
```

        # Hack to workaround that eu-north-1 is not in the registry validation table yet, giving this
        # endpoint explicitly bypasses the check... (the eu-north-1 region in config.yml is validated)
        REGISTRY_STORAGE_S3_REGIONENDPOINT: "s3.eu-north-1.amazonaws.com"
```

That this works fine, leads me to believe that the check could just be dropped, it's not anything the S3 SDK itself cares about as long as it gets its endpoint (though, maybe AWS has a different URL endpoint format for some regions so you simply can't paste it together like this, a bit improbable though).

**Comment by qvistgaard** [comment]
Yeah, it works. But it doesn't work with irsa enabled

**Comment by milosgajdos** [comment]
This should be fixed in the latest release: https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1

**Comment by milosgajdos** [comment]
Closing as fixed in the latest release.
