### ISSUE TITLE
Environment variable ending with '!' fails in docker run 

### ISSUE THREAD

**Issue by shopizer-ecommerce** [distribution/distribution#2882]
Declaring an environment variable ending with ! (exclamation mark) causes an error when running docker

docker run -e "secretKey=mykey!"  -v /volume/shopizer:/out purgeBatch

-bash: !": event not found

if i change mykey! with mykey it works correctly

**Comment by P1ng-W1n** [comment]
That's a typical issue with bash bellow version 4.3. 

You can reproduce the same issue pretty easily:
$ docker run --rm -it bash:4.2 bash
bash-4.2# echo "Reboot your instance!"
bash: !": event not found

There are two ways to solve that: Either use single quotes instead of double quotes, or disable the history substitution:

$ docker run -it --rm bash:4.2 bash 
bash-4.2# echo "Reboot your instance!"
bash: !": event not found
bash-4.2# echo 'Reboot your instance!'
Reboot your instance!
bash-4.2# set +H
bash-4.2# echo "Reboot your instance!"
Reboot your instance!

Background: '!' is a special character in bash, used to refer to a previously executed command.

**Comment by milosgajdos** [comment]
This is the wrong repo to report this issue in. Please ask in https://github.com/docker/cli or https://github.com/moby/moby
