### ISSUE TITLE
docker prevents using chrt 

### ISSUE THREAD

**Issue by Jhon0510** [distribution/distribution#2910]
Hello,

I have a Docker-ce version 18.09.1 installed on a CentOS Linux release 7.5.1804 (Core).
I am trying to change the priority of a task using chrt (for e.g sudo chrt -f 99 whoami). But the following error occurs:
         chrt:failed to set pid 0's policy: Operation not permitted
Once i reboot the machine, the chrt works well (because the Docker daemon is not working). As soon  as i start Docker (sudo systemctl start docker) the chrt does not work anymore (on the same console, it continues to work, but  if you connect to other consoles, it stops working).
The only founded solution is to change the "rt_runtime_us" value of the kernel to -1.  But using 100% of CPU for RT is dangerous. Is it possible to solve this problem in another way?

**Comment by flhofer** [comment]
Hello Jhon,

Docker uses CGroups to separate and allocate resources. Depending on your configuration, it might be configured to use some part of them exclusively, i.e. forcing partitioned scheduling. I know that this is the case for EDF scheduled tasks, where the admission test of the kernel's scheduler fails if it doesn't have the possibility of 100% real-time allocation as it couldn't guarantee deadlines otherwise. Wouldn't be surprised if there is a similar limitation for FIFO but I would need to check the source to know for sure.
So, you might need to play around with Control groups to make it work. 

Good luck

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to report this in. Please ask in https://github.com/moby/moby/
