### ISSUE TITLE
Documentation mismatched!

### ISSUE THREAD

**Issue by namnx228** [distribution/distribution#3506]
I notice that the `minimumtls` field is introduced in the doc: https://github.com/distribution/distribution/blob/main/docs/configuration.md#tls, leading to the general docker document having the same info: https://docs.docker.com/registry/configuration/#tls. However, we have not yet had this configuration in the registry latest release and in the official docker image. Therefore, the doc is now introducing a `not-yet-in-place` configuration , making a confusion for people following the documentation on https://docs.docker.com/registry/configuration/.

**Comment by thaJeztah** [comment]
I suspect this is because the docker documentation uses the `release/2.7` release branch as source for the documentation. Under normal ("most") situations, this should match the latest release from that branch (new features generally aren't back ported, only bug fixes, which don't bring user-facing changes), but it looks like https://github.com/distribution/distribution/pull/3384 back ported this feature (but has not been released).


/cc @milosgajdos @waynr

**Comment by milosgajdos** [comment]
@namnx228 with the latest release out last night https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1 I'm inclined to close this issue 

Furthermore, the docs are now owned by this GH organization and no longer by Docker Inc. They're available at https://distribution.github.io/distribution/

**Comment by thaJeztah** [comment]
Yes, we can close this one; the docker documentation was updated, and no longer copies the docs, but instead links to the distribution documentation at https://distribution.github.io/distribution/

For older versions of the registry, the docs in the github repository can be used, e.g.;  for the v2.8.3 release; https://github.com/distribution/distribution/tree/v2.8.3/docs
