### ISSUE TITLE
S3 Backend: panic in ListObjectsV2Pages

### ISSUE THREAD

**Issue by rchernobelskiy** [distribution/distribution#3533]
I'm getting the following panic when I run `garbage-collect -d` on master, I think it may be related to https://github.com/distribution/distribution/pull/3480
```
EBU[0000] s3aws.ListObjectsV2Pages(cache/docker/registry/v2/repositories/)  environment=development go.version=go1.17.3 instance.id=707de1f9-fe1b-4513-bf79-7758f39f3af6 service=registry trace.duration=355.9452ms trace.file=/go/src/github.com/distribution/distribution/registry/storage/driver/s3-aws/s3.go trace.func="github.com/distribution/distribution/v3/registry/storage/driver/s3-aws.(*driver).doWalk" trace.id=0834e3c8-9506-4325-951c-5078af5a154d trace.line=961 trace.parent.id=9dc2a782-a261-466f-903d-5df1fbcaaacb
DEBU[0000] s3aws.Walk("/docker/registry/v2/repositories")  environment=development go.version=go1.17.3 instance.id=707de1f9-fe1b-4513-bf79-7758f39f3af6 service=registry trace.duration=356.1477ms trace.file=/go/src/github.com/distribution/distribution/registry/storage/driver/base/base.go trace.func="github.com/distribution/distribution/v3/registry/storage/driver/base.(*Base).Walk" trace.id=9dc2a782-a261-466f-903d-5df1fbcaaacb trace.line=232
panic: runtime error: slice bounds out of range [33:7]

goroutine 1 [running]:
github.com/distribution/distribution/v3/registry/storage.handleRepository({0xfbc848, 0xc000957780}, {0xc000140740, 0x20}, {0x0, 0x0}, 0xc000121100)
	/go/src/github.com/distribution/distribution/registry/storage/catalog.go:143 +0x205
github.com/distribution/distribution/v3/registry/storage.(*registry).Enumerate.func1({0xfbc848, 0xc000957780})
	/go/src/github.com/distribution/distribution/registry/storage/catalog.go:68 +0x34
github.com/distribution/distribution/v3/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc000122d00, 0xc1)
	/go/src/github.com/distribution/distribution/registry/storage/driver/s3-aws/s3.go:1009 +0x4aa
github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc00013c1e8, {0xfbbe00, 0xc0000dafc0}, 0xc00027c0a0, 0xc0006077b8, {0x0, 0x0, 0x0})
	/go/src/github.com/distribution/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:6095 +0x1c4
github.com/distribution/distribution/v3/registry/storage/driver/s3-aws.(*driver).doWalk(0xc000122c00, {0xfbbe00, 0xc0000daee0}, 0xc00061f870, {0xc000156870, 0x0}, {0x0, 0x0}, 0xc000204140)
	/go/src/github.com/distribution/distribution/registry/storage/driver/s3-aws/s3.go:973 +0x3a5
github.com/distribution/distribution/v3/registry/storage/driver/s3-aws.(*driver).Walk(0x0, {0xfbbe00, 0xc0000daee0}, {0xc000140740, 0x20}, 0x0)
	/go/src/github.com/distribution/distribution/registry/storage/driver/s3-aws/s3.go:933 +0x159
github.com/distribution/distribution/v3/registry/storage/driver/base.(*Base).Walk(0xc00037e1d0, {0xfbbb98, 0xc000268d80}, {0xc000140740, 0xd4fe60}, 0x7f2032103a01)
	/go/src/github.com/distribution/distribution/registry/storage/driver/base/base.go:239 +0x2b5
github.com/distribution/distribution/v3/registry/storage.(*registry).Enumerate(0xc0000dae70, {0xfbbb98, 0xc000268d80}, 0xc000121100)
	/go/src/github.com/distribution/distribution/registry/storage/catalog.go:67 +0xd4
github.com/distribution/distribution/v3/registry/storage.MarkAndSweep({0xfbbb98, 0xc000268d80}, {0xfd2418, 0xc00037e1d0}, {0xfc1498, 0xc0000dae70}, {0x6, 0x1})
	/go/src/github.com/distribution/distribution/registry/storage/garbagecollect.go:40 +0x1de
github.com/distribution/distribution/v3/registry.glob..func3(0x1598580, {0xc0004e9680, 0x3, 0x3})
	/go/src/github.com/distribution/distribution/registry/root.go:80 +0x3ff
github.com/spf13/cobra.(*Command).execute(0x1598580, {0xc0004e9650, 0x3, 0x3})
	/go/src/github.com/distribution/distribution/vendor/github.com/spf13/cobra/command.go:766 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1598320)
	/go/src/github.com/distribution/distribution/vendor/github.com/spf13/cobra/command.go:852 +0x2dc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/distribution/distribution/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/github.com/distribution/distribution/cmd/registry/main.go:24 +0x25
```

**Comment by CollinShoop** [comment]
Looks like the problematic slice is coming from [storage/catalog.go:143](https://github.com/distribution/distribution/blob/5bda06924315e1f8082c2d50215b14233a63e512/registry/storage/catalog.go#L143) as part of `handleRepository`
```
repo := filePath[len(root)+1:]
```
which to me implies `filePath` is shorter than `root`, which definitely seems wrong. Would you be able to add some logging to see which root and path are provided here when this happens?

**Comment by rchernobelskiy** [comment]
Yep, exactly. The two values it panics on for `root` and `filePath` are:
```
/docker/registry/v2/repositories
/docker
```

Adding the following stops the panic and functionality seems ok, but not sure if it remains correct:
```
	if len(filePath) <= len(root) {
		return nil
	}
```

**Comment by CollinShoop** [comment]
@rchernobelskiy Those results are definitely not what I expected, and I'm not sure how it's possible. Would you possibly be able to try reproducing this issue on this branch https://github.com/distribution/distribution/pull/3538 in which I effectively rolled back `_catalog` to use the prior recursive Walk implementation that was used before #3480?  At lease then we can narrow it down a bit further.

**Comment by aaronlehmann** [comment]
We hit this issue as well. Seems like this has been known for a long time - can we please move forward with one of the fixes (sounds like #3685 should address this?).

**Comment by aaronlehmann** [comment]
BTW, #3685 appears to fix this for me.

**Comment by rchernobelskiy** [comment]
Since we couldn't get this working reliably, we switched to a different approach: changing the s3 path once a month, and then letting s3 automatically clean up anything older than 33 days.

**Comment by splucs** [comment]
I believe I've identified the issue:

### Context
The desired logic for the catalog endpoint is not to just walk over all objects of the s3 bucket with the desired prefix but also over all directories where these objects may be contained. For example, when listing all repositories (`root = /docker/registry/v2/repositories`), the driver walks not just over `/docker/registry/v2/repositories/<repo>/_layers/sha256/<sha>/link` but also over `/docker/registry/v2/repositories/<repo>`, `/docker/registry/v2/repositories/<repo>/_layers`, `/docker/registry/v2/repositories/<repo>/_layers/sha256` and `/docker/registry/v2/repositories/<repo>/_layers/sha256/<sha>`.

The way this is achieved is by using the fact that the s3 walk endpoint returns objects in lexicographical order. Whenever a new object is processed, the common prefix of the current object and the previous object is calculated and all prefixes of the current object after the common prefix are considered unprocessed directories. For example, if the last object was `/docker/registry/v2/repositories/<repo>/_layers/sha256/<sha1>/link` and the current object is `/docker/registry/v2/repositories/<repo>/_layers/sha256/<sha2>/link`, the common prefix is `/docker/registry/v2/repositories/<repo>/_layers/sha256` and both `/docker/registry/v2/repositories/<repo>/_layers/sha256/<sha2>` and `/docker/registry/v2/repositories/<repo>/_layers/sha256/<sha2>/link` are considered new paths to be processed. Internally this is implemented by maintaining a `prevDir` that holds the base directory of the last processed s3 object.

There is a corner case, however, that is the first object to be processed. It doesn't have a previous object but we must only process its paths if they are under the root (`root = /docker/registry/v2/repositories`) of the walk. This is achieved by setting the last processed path to the root so the first iteration diffs the paths from the root and the first object.

### Problem
The problem is that the path diff'ing function uses a path relative to the root directory of the s3 bucket (`/docker/registry/v2/repositories`) but the initial `prevDir` is being set to the absolute path within the bucket (`<root dir>/docker/registry/v2/repositories`).

If the root directory is not empty, the common prefix of the initial prevDir and the first object is empty, which causes the string `/docker` to be considered a path to be processed. The catalog endpoint assumes that all paths returned are subpath of `/docker/registry/v2/repositories`, which is not true for `/docker`, which causes the panic.

### Solution
The fix is to set the initial `prevDir/` using a path relative to the root directory and not relative to the entire bucket. I've tested locally by changing the initial setting of the prevDir variable from `prevDir = prefix + path` to `prevDir = strings.Replace(path, d.s3Path(""), prefix, 1)` and I no longer get panics on the catalog endpoint.
