### ISSUE TITLE
Plan for the next release

### ISSUE THREAD

**Issue by namnx228** [distribution/distribution#3537]
Do we have any plans to have the next `v2 ` release? There is some security fixes in branch `release/2.7` but is missing in the latest release.

**Comment by spider-network** [comment]
I am also wondering, the last Tag was created at the beginning of 2019. But I see many commits over the last two years. With the latest images that are pushed to dockerhub we still run in rate limit issue at dockerhub. Is the version check done by a HEAD request? because HEAD requests are not counted

**Comment by dsaydon90** [comment]
we are looking forward for the next release too 😎

**Comment by jeffreygolden** [comment]
Chiming in, a fix was merged for images over 10GB on S3-backed registries, we would love to have this in a release as it's a blocker for us!

Is there anything I can do to help cut a new release?

**Comment by DavidSpek** [comment]
The above mentioned fix for S3 was included in release v2.8.2. All effort is now being put into the v3 release.

**Comment by milosgajdos** [comment]
Closing, we've just made the first `v3` release Closing as should be fixed in https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1
