### ISSUE TITLE
There is a surprising increase in transitive dependencies when we switch to distribution v3

### ISSUE THREAD

**Issue by pacoxu** [distribution/distribution#3587]
When I migrate to github.com/distribution/distribution/v3 from v2 in kubernetes https://github.com/kubernetes/kubernetes/pull/107211, we got a surprising increase in transitive dependencies for this switch. See https://github.com/kubernetes/kubernetes/pull/107211#issuecomment-1006698414. 

Firstly, we thought about maintaining the stable part in kubernetes utils repo. However, owners think it would be better if distribution/distribution spilt the library. 
> I may suggest to upstream distribution/distribution folks that splitting that library and doing symbol refs might be the right thing to do long term.

```
-	dockerref "github.com/docker/distribution/reference"
+	dockerref "github.com/distribution/distribution/v3/reference"
```
The only part we are using in Kubernetes project is like above.

**Comment by pacoxu** [comment]
See comments in https://github.com/kubernetes/utils/pull/232.

**Comment by milosgajdos** [comment]
beware `v3` is the `edge` -- we make no guarantees about its stability until a stable release and yeah there are a ton of new deps accrued over the years, unfortunately

**Comment by pacoxu** [comment]
> beware `v3` is the `edge` -- we make no guarantees about its stability until a stable release and yeah there are a ton of new deps accrued over the years, unfortunately

Of course, there are no guarantees on that.

> This aligns similar to what openshift did (to focus on the stable "api" parts of distribution and image references that shouldn't be coupled to serving or client behavior) in https://github.com/openshift/library-go/tree/master/pkg/image/internal, so it looks good from that perspective.
> 
> I may suggest to upstream distribution/distribution folks that splitting that library and doing symbol refs might be the right thing to do long term.

In long-term repo management, this would be a suggested way.

**Comment by Jamstah** [comment]
I posted about this [on slack](https://cloud-native.slack.com/archives/C01GVR8SY4R/p1657285881993909) to see if there is any real appetite from the maintainers for making this split, I'd be happy to do the legwork if it's valuable, copying the message here for tracking:

I did a quick search of projects that may benefit from this: https://github.com/search?q=github.com%2Fdocker%2Fdistribution%2Freference+language%3Ago&type=code

It looks like there are plenty of projects importing only the reference package for parsing and don't need the whole module.

I believe the ask in this issue would require:
- Making [github.com/distribution/reference](http://github.com/distribution/reference)
- Moving the reference and digestset packages to it
- Setting up the github actions to build/test/lint it
- Making a v1 release
- Updating [github.com/distribution/distribution/v3/reference](http://github.com/distribution/distribution/v3/reference) (and digestset) with symbol refs to the new module so that we don't break people already using it (although most people still point to v2 right now, so we could skip that and say its a breaking change. I would keep the symbols.)
- Updating [github.com/distribution/distribution/](http://github.com/distribution/distribution/) code to use the new module

Then for future development, any changes to the reference (and digestset, because it's used by reference) package would need to be done in the new module before being used in the registry, which could slow down some development, but it's pretty stable, the last functional change to the externals being back in 2019 that I could find.

**Comment by thaJeztah** [comment]
I'm working on cleaning up and synchronizing the implementations of the `reference` package. Containerd forked this package, and after forking, the code started to diverge (on both sides), e.g. distribution/distribution was missing the `Sort()`, whereas containerd's fork was missing the support for IPv6 (related to  https://github.com/kubernetes/kubernetes/issues/104491), as well as some optimizations made in distribution/distribution. I think one of the reasons for containerd to fork the package was its dependency on [github.com/distribution/distribution/digestset](https://github.com/distribution/distribution/tree/e0281dc609a025383e9bd6505dc69f07e7bae4d9/digestset) (which now _also_ lives in [github.com/opencontainers/go-digest/digestset](https://github.com/opencontainers/go-digest/tree/084376bb543d4ce80b030a77a6f51f3b3fd861dc/digestset), as well as the distribution/distribution dependency to bring in many (indirect) dependencies.

- https://github.com/distribution/distribution/pull/3774 (to separate the `reference` package from `digestset`)
- https://github.com/cncf/cncf-fuzzing/pull/235 (related to the above)
- https://github.com/containerd/containerd/pull/7635 is syncing containerd's fork with the upstream (distribution/distribution)
- https://github.com/distribution/distribution/pull/3776 (upstreaming a patch from containerd)
- https://github.com/distribution/distribution/pull/3777 (upstreaming new functionality from containerd)
- https://github.com/distribution/distribution/pull/3775 (deprecating and removing the (now unused) digestset package)
- https://github.com/cncf/cncf-fuzzing/pull/236 (related to the above)

With the above in place, the `reference` package is mostly self-contained, only having github.com/opencontainers/go-digest as dependency, which makes it a good candidate to be moved to its own module (and repository?), which would;

- address https://github.com/distribution/distribution/issues/3587
- address https://github.com/kubernetes/kubernetes/issues/103849
- (indirect) https://github.com/istio/istio/pull/34254
- address https://github.com/kubernetes/kubernetes/issues/104491
- prevent creating even _more_ forks, such as initially proposed in;
    - https://github.com/kubernetes/kubernetes/pull/107211
    - https://github.com/kubernetes/utils/pull/232

/cc @dims @liggitt

**Comment by dims** [comment]
@thaJeztah worth trying again! yes.

Also note that in k8s go.mod/sum does not have containerd/containerd any more So we have one less thing to worry about.

**Comment by Jamstah** [comment]
As above I'd be happy to help out if its useful.

**Comment by pacoxu** [comment]
I recently worked on containerd image pull metrics, it will call `reference` package as well. 
https://github.com/containerd/containerd/pull/7313

Thanks for updating on this.

**Comment by Jamstah** [comment]
Now the PRs @thaJeztah mentions above are merged, importing just github.com/distribution/distribution/v3/reference is clean.

Should we close this pr? The only thing we would gain from splitting it into a separate repository is splitting the release lifecycle, do we want that?

**Comment by pacoxu** [comment]
> Now the PRs @thaJeztah mentions above are merged, importing just github.com/distribution/distribution/v3/reference is clean.
> 
> Should we close this pr? The only thing we would gain from splitting it into a separate repository is splitting the release lifecycle, do we want that?

@Jamstah  If importing `github.com/distribution/distribution/v3/reference` is the choice, a go.mod should be added to https://github.com/distribution/distribution/tree/main/reference.

Currently, I would get an error if I want to import the reference directly
> invalid version: missing github.com/distribution/distribution/v3/reference/go.mod at revision xxx

**Comment by Jamstah** [comment]
I'm no go expert, so tell me if I'm wrong, and adding another go.mod may still be the right thing to do, but I checked to see if it worked in go 1.19. From what I can see, importing the one package won't pull in the extra dependencies and will compile just fine: https://github.com/Jamstah/go-prune-test

**Comment by pacoxu** [comment]
Thanks for the confirmation. I will check.

**Comment by DavidSpek** [comment]
Maybe @milosgajdos can weigh in here.

**Comment by milosgajdos** [comment]
I need to pull in @thaJeztah here as he's the maintainers of `moby/moby` and the `reference` package is used at least in the image pull code:

https://github.com/moby/moby/blob/d83ead84340ca8a586186a13d4d7169931593b5e/daemon/images/image_pull.go#L12

**Comment by Jamstah** [comment]
I thought that's what the symbol refs in this repo would be for, to not break people who import from here while allowing anyone who changes their import to refer to it cleanly?

**Comment by milosgajdos** [comment]
Yeah, I get that, just wanna give other co-maintainers heads up our future intent 🤝  🤷‍♂️

**Comment by milosgajdos** [comment]
I am not against ripping it out. I would also like to rip out all the drivers (other than the in-memory and filesystem ones) into their dedicated repos...but that's a discussion for a separate issue. I dont wanna hijack this one

**Comment by Jamstah** [comment]
Yes, that would be good too, I'm even less sure about how that would work :)

Do we have an issue open for it at all?

**Comment by milosgajdos** [comment]
> Yes, that would be good too, I'm even less sure about how that would work :)
> 
> Do we have an issue open for it at all?

Created one here https://github.com/distribution/distribution/issues/3988

**Comment by thaJeztah** [comment]
Yes, this one was still on my list; I think the last change on my list was https://github.com/distribution/distribution/pull/3803, but looks like that one still needed some debating.

I'm personally fine with keeping that improvement for a later exercise, and to prepare a repository in which I extract the code (preserving history).

However (I'll comment on that other issue as well), we probably need to discuss first where that repository should live.

I had some discussion with @dmcgowan about "where to move it", because the "reference" package does not really have anything to do with either "CNCF" or "OCI"; the package is codifying the conventions used by the Docker Engine, "pre OCI" when only "one" registry existed: "Docker Hub" (or "The Docker Index" before that), and in which some hard-coded decisions are made from that perspective (non-fully-qualified names, such as `ubuntu` means `docker.io/library/ubuntu:latest`), and "first element is either a namespace (path element) or a hostname (contains a dot (`.`) or colon (`:`)), or is an IP-address.

While all of that still applies for the Docker Engine, and runtimes that want to copy the Docker Engine "UX", the main purpose is for it to exist is for backward-compatibility with that UX, and it (honestly) is very messy in various parts (hard-coded domain-names, such as `index.docker.io`, `registry-1.docker.io`). Having a separate module for this package would allow for a "canonical" implementation of these conventions, and allow for projects to transition to changes (if progress is made) separate from other dependencies in this repository.

It's a frequently recurring topic (internally at least), as we really want to get rid of that logic, or at least: "limit the handling where possible" (normalize references on the way in, and use fully-qualified names where possible), and there's continuing discussions on getting out of the "hard-coded domains" situation, but changes in that area depend on Docker (Inc.); we got everyone into this mess, so should also work on getting out of it.

To cut a long story short; my initial proposal was to extract the package, and move it into a repository in the `moby` org, which is where most of this logic originated from, and where the code to build the Docker Engine is located. Governance of the moby org / project is separate from Docker (Inc.), which also makes it slightly easier to add maintainers. I'm an owner on the Moby GitHub org, so would be able to do such a move; baring any legalese, as the code was donated to the CNCF (it's Apache 2, so "copying" the code wouldn't be an issue, but we probably need concensus on the change among maintainers to _replace_ the package with the code in the new location and to consider it the "canonical" location).

OTOH, as mentioned above, parts of these depend on Docker (Inc.) to make changes, so from that perspective, it would make sense to move it into the `docker` org, however, that would at least require assistance from an owner in that GitHub org.

**Comment by thaJeztah** [comment]
OH! Sorry, I just realised the new issue is about storage drivers, not about the reference package 😂 🙈 

My comment above still applies though; we should discuss if we want the `reference` package to be split to its own module, and where that module should live.

**Comment by Jamstah** [comment]
On, where to move it: I think we need a new OCI spec (reference-spec) to go along side runtime-spec, distribution-spec, and image-spec. Then, in the same way this repo is a reference implementation of the OCI registry spec, I think we could have distribution/reference be a reference implementation of the reference-spec.

The OCI spec is where we could clarify the existing behaviour, and potentially add things like the schemes that skopeo and others have started using to refer to images in places other than registries.

While this happens, I think this org is still a perfectly good place to host the code.

**Comment by Jamstah** [comment]
Related discussion: https://github.com/kubernetes/kubernetes/issues/46255 (@stevvooe fyi)

**Comment by Jamstah** [comment]
@milosgajdos are you happy to make a distribution/reference repo? I'm happy to pr in the structure I made which will allow discussion. (https://github.com/Jamstah/reference)

I don't think we need full history, just a reference back to the commit that diverged from this repo.

**Comment by milosgajdos** [comment]
Should we call it simply just `reference`?

**Comment by Jamstah** [comment]
I would.

**Comment by thaJeztah** [comment]
> I don't think we need full history, just a reference back to the commit that diverged from this repo.

I'd really like to preserve history, not just to find back history for specific parts of the code, but also to give attribution to the contributors who provided the code.

Let me give it a quick attempt.

**Comment by thaJeztah** [comment]
Here's a quick attempt; didn't add the README, because _most of that_ probably needs to be adjusted, but I think all other essential parts are there; https://github.com/thaJeztah/reference

**Comment by milosgajdos** [comment]
Ok, I've just created https://github.com/distribution/reference with basic options (same license as the main repo), etc.

I tend to agree with @thaJeztah: if we can preserve the `git` history, that'd be grand for attribution, etc.

**Comment by Jamstah** [comment]
Sounds good to me!

**Comment by milosgajdos** [comment]
@thaJeztah do you wanna go ahead and do the same thing on the newly created repo?

**Comment by thaJeztah** [comment]
Can move it there

**Comment by thaJeztah** [comment]
@milosgajdos can you remove the repo and make sure it's empty? (looks like you picked the "add license" and such options.

**Comment by milosgajdos** [comment]
> @milosgajdos can you remove the repo and make sure it's empty? (looks like you picked the "add license" and such options.

Sure.

**Comment by thaJeztah** [comment]
PR to migrate to the new module;

- https://github.com/distribution/distribution/pull/4031

We can clean up the new repository a bit if needed, and tag a release after that

**Comment by Jamstah** [comment]
Closing this issue now that the reference library is in its own repo: https://github.com/distribution/reference

**Comment by pacoxu** [comment]
Thanks for the effort.
