### ISSUE TITLE
testing: replace legacy `gopkg.in/check.v1`

### ISSUE THREAD

**Issue by thaJeztah** [distribution/distribution#3884]
This repository is using `gopkg.in/check.v1` as a testing framework. While [`gopkg.in/check.v1`](https://pkg.go.dev/gopkg.in/check.v1) was a good solution at the time it was introduced, it's not very actively maintained, and doesn't take advantage of recent improvements in Go's testing package.

We should replace this framework with a more actively maintained, and commonly used framework (also to reduce extra module dependencies on consumers of this repository / module).

Some alternatives that are commonly used:

- [`github.com/stretchr/testif`](https://pkg.go.dev/github.com/stretchr/testify) / [`github.com/stretchr/testify/suite`](https://pkg.go.dev/github.com/stretchr/testify/suite)
- [`gotest.tools/v3`](https://pkg.go.dev/gotest.tools/v3)

Related / similar;

- https://github.com/moby/moby/pull/39799

**Comment by deleteriousEffect** [comment]
We've had good results with testify for new tests and have looked into removing check.

The biggest issue with removing check is that the driver test suites use check heavily and cover a lot of important functionality. Not impossible by any means, but it is a fair amount of effort since there's not a 1-to-1 way to swap out check for testify, at least.

**Comment by milosgajdos** [comment]
There is https://pkg.go.dev/github.com/stretchr/testify/suite

We just never really put any effort into removing check1. It is non-trivial I agree!

**Comment by squizzi** [comment]
I was looking at converting `check.v1` to `testify/suite` today since I've used `testify/suite` in the past and have generally liked it.  Alot of the functionality used by check has a relatively simple 1:1 with `testify/suite` making this refactor a little more straightforward.  I'd be interested in tackling this.

**Comment by DavidSpek** [comment]
@squizzi Is this still something you think you’ll get around to and/or want to do?

**Comment by squizzi** [comment]
@DavidSpek I've got something about 70% done, I'm on vacation right now and plan to finish it when I return next week.

**Comment by DavidSpek** [comment]
Awesome!

**Comment by milosgajdos** [comment]
@squizzi have you made any progress with this? It'd be fantastic to bin `gopkg.in/check.v1`
