### ISSUE TITLE
HTTP GET on /v2/<repo>/manifests/<tag> fails with read-only filesystem

### ISSUE THREAD

**Issue by xAt0mZ** [distribution/distribution#4437]
### Description

Hi there,
At Portainer we developed a feature to browse registries (repositories / tags)

One of our customers has a read-only access to its registry from Portainer for security reasons.
While our customer understands he cannot perform mutations (remove images or retags), he is not able to simply browse the registry.

Internally we leverage the v2 API for the browse feature (GET _catalog, repo list, repo tags, blobs, etc).

A request `GET /v2/repo/manifests/tags` with `Accept: application/vnd.docker.distribution.manifest.v2+json` works perfectly (as per the registry logs below)
```json
{
  "time":"2024-08-14T17:40:53.412694209Z",
  "level":"info",
  "msg":"response completed",
  "go.version":"go1.20.8",
  "http.request.host":"dockerreg.example.com:5000",
  "http.request.id":"50a0289b-f505-4abf-994d-7944821ceabb",
  "http.request.method":"GET",
  "http.request.referer":"https://portainer.example.com/",
  "http.request.remoteaddr":"192.168.1.20",
  "http.request.uri":"/v2/myimage/manifests/3.0",
  "http.request.useragent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
  "http.response.contenttype":"application/vnd.docker.distribution.manifest.v2+json",
  "http.response.duration":"6.690765ms",
  "http.response.status":"200",
  "http.response.written":"741"
}
```

However `GET /v2/repo/manifests/tag` with `Accept: application/vnd.docker.distribution.manifest.v1+json` errors with the following logs.
```json
{
  "time":"2024-08-14T17:40:53.417155977Z",
  "level":"error",
  "msg":"error putting into main store: filesystem: mkdir /var/lib/registry/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d5: read-only file system",
  "go.version":"go1.20.8",
  "http.request.host":"dockerreg.example.com:5000",
  "http.request.id":"542ce73f-bb7d-44be-9e1d-014d7e576958",
  "http.request.method":"GET",
  "http.request.referer":"https://portainer.example.com/",
  "http.request.remoteaddr":"192.168.1.20",
  "http.request.uri":"/v2/myimage/manifests/3.0",
  "http.request.useragent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
  "vars.name":"myimage",
  "vars.reference":"3.0"
}
```

We are trying to figure out what could be the reason behind that? Why would the registry need to create a directory in this case?
Are there any specifics we should be aware of when it comes to reads/writes to the FS? Is there a documentation somewhere of actions that require write accesses to the registry?

### Reproduce

-

### registry version

-

**Comment by thaJeztah** [comment]
Passing that accept header likely triggers the legacy conversion code that converts manifests to the v1 format https://github.com/distribution/distribution/blob/fc0b89c6f7dd308919ce7ae78da9d4d5cb3ca207/docs/content/spec/manifest-v2-2.md?plain=1#L276

https://github.com/distribution/distribution/blob/fc0b89c6f7dd308919ce7ae78da9d4d5cb3ca207/registry/handlers/manifests.go#L173

**Comment by xAt0mZ** [comment]
@thaJeztah thanks

I don't get which step of the conversion process would imply creating a blob directory tho. We simply try to fetch the v1 schema to get the layers history/details (v1.history.v1compatibility).

We can use the `/v1/<repo>/blobs/<digest>` API for that matter, but I guess it also implies having the registry try to create a blob directory at some point?

**Comment by thaJeztah** [comment]
> We simply try to fetch the v1 schema to get the layers history/details (v1.history.v1compatibility).

You wouldn't need schema 1 for that; the converted schema is all based on the v2 one, so won't contain information that isn't present in the v2 one. Schema v1 has been deprecated for a long time (Schema 2 was introduced in 2015 and deprecated v1; https://github.com/distribution/distribution/commit/e564ac59c3694d7792c661898d5194ede4267f97). I would highly recommend _NOT_ depending on v1 for any use-case. The v1 specification on its own is insecure (not content-addressable), and the conversion logic in registries will very likely Go away in the near future.

> We can use the /v1/<repo>/blobs/<digest> API for that matter, but I guess it also implies having the registry try to create a blob directory at some point?

That would require running a v1 registry, which is no longer supported by any current client (and for which the code reached EOL more than 10 Years ago; https://github.com/docker-archive/docker-registry). 


The history information (if included, as it's _optional_) will be in the image _config_, not the image _manifest_. See the "history" item under "Properties" in the OCI image spec; https://github.com/opencontainers/image-spec/blob/v1.1.0/config.md#properties

The history in the v1 schema is produced from that metadata. For example, here's the v2 manifest;

```bash
curl -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' "http://localhost:5001/v2/myimage/manifests/latest"
# {
#    "schemaVersion": 2,
#    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
#    "config": {
#       "mediaType": "application/vnd.docker.container.image.v1+json",
#       "size": 7314,
#       "digest": "sha256:c57a9d25c483f409effdbddb59c2afddec4454c435cff6094521aa9296911ce9"
#    },
# .......
```

The `config` has a reference to the digest of the config (`sha256:c57a9d25c483f409effdbddb59c2afddec4454c435cff6094521aa9296911ce9` in this case); I'm using `jq` here to only show the history;

```bash
 curl -s "http://localhost:5001/v2/myimage/blobs/sha256:c57a9d25c483f409effdbddb59c2afddec4454c435cff6094521aa9296911ce9" | jq .history
[
  {
    "created": "2019-01-30T22:19:46.858068773Z",
    "created_by": "/bin/sh -c #(nop) ADD file:91fb97ea3549e52e7b6e22b93a6736cf915c756f3d13348406d8ad5f1a872680 in / "
  },
...
````

:warning: but be aware that the history metadata is both _optional_ and for informational purposes; there is no verification for any of the information in the history to actually match the steps used to produce the image. Depending on what tool was used to produce the image, history may not be available. Current versions of BuildKit started to include SBOMS and attestations and other metadata which, depending on your use-case, may be more accurate.

> I don't get which step of the conversion process would imply creating a blob directory tho.

The v1 image will produce different digests. I don't know the full history behind the implementation, but very likely it writes the result to disk both to get the checksums, to have the new digests available for them to be pulled, and possibly for optimisation (preserving the results of the converted image).

I did a quick test to confirm that this is related to the conversion, and it looks indeed that it writes to the filesystem. Here's the steps I took;

Run a registry, but using a non-standard location for the storage, so that it's not stored in a volume;

```bash
docker run -d --name registry -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry2 -p 5001:5000 registry:2
```

Push an image;

```bash
docker push localhost:5001/myimage
```

Commit the container to an image; the image will now have the data of the pushed image "baked in";

```bash
docker commit registry registry-temp
```

Remove the registry container and start a new one, but this time using the committed image;

```bash
docker rm -fv registry
docker run -d --name registry -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry2 -p 5001:5000 registry-temp
```

Access the manifest with `application/vnd.docker.distribution.manifest.v2+json` (which should produce a schema 2 manifest);

```bash
curl -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' "http://localhost:5001/v2/myimage/manifests/latest"
# {
#    "schemaVersion": 2,
#    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
#    "config": {
#       "mediaType": "application/vnd.docker.container.image.v1+json",
#       "size": 7314,
#       "digest": "sha256:c57a9d25c483f409effdbddb59c2afddec4454c435cff6094521aa9296911ce9"
#    },
# .......
```

Check there's no diff on the registry container's filesystem;

```bash
docker diff registry
# empty
```

Access the manifest again, this time with `application/vnd.docker.distribution.manifest.v1+json` (this should produce a legacy "v1" manifest (which was converted from the original v2));


```bash
curl -H 'Accept: application/vnd.docker.distribution.manifest.v1+json' "http://localhost:5001/v2/myimage/manifests/latest"
# {
#    "schemaVersion": 1,
#    "name": "myimage",
#    "tag": "latest",
#    "architecture": "amd64",
#    "fsLayers": [
# ...
```

Check the container again for filesystem changes; this time a diff is shown for the converted manifest;

```bssh
docker diff registry
C /var
C /var/lib
C /var/lib/registry2
C /var/lib/registry2/docker
C /var/lib/registry2/docker/registry
C /var/lib/registry2/docker/registry/v2
C /var/lib/registry2/docker/registry/v2/repositories
C /var/lib/registry2/docker/registry/v2/repositories/myimage
C /var/lib/registry2/docker/registry/v2/repositories/myimage/_layers
C /var/lib/registry2/docker/registry/v2/repositories/myimage/_layers/sha256
A /var/lib/registry2/docker/registry/v2/repositories/myimage/_layers/sha256/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
A /var/lib/registry2/docker/registry/v2/repositories/myimage/_layers/sha256/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/link
C /var/lib/registry2/docker/registry/v2/blobs
C /var/lib/registry2/docker/registry/v2/blobs/sha256
A /var/lib/registry2/docker/registry/v2/blobs/sha256/a3
A /var/lib/registry2/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
A /var/lib/registry2/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/data

```

**Comment by xAt0mZ** [comment]
Thanks a lot for the details and reproduction/verification steps!

> > We can use the `/v1/<repo>/blobs/<digest>` API for that matter,
>
> That would require running a v1 registry, which is no longer supported by any current client (and for which the code reached EOL more than 10 Years ago; https://github.com/docker-archive/docker-registry).

Big woopsie typo from me, we definitely only use the v2 API...

This feature was made a very long time ago (~6 years), and at that time we had user reporting browse not working, as they were still using v1 images. We didn't rework it since then (our bad).

ATM we are doing
* get v2 manifest
* get v1 manifest
* get image config from v2.config.digest

When the imageConfig (v2/<repo>/blobs/<digest>) exists, we pick it, and keep the `v1.history.v1compatibility` for v1 legacy images.

We will ditch the v1 part as per your recommendations

**Comment by thaJeztah** [comment]
Yeah, I would definitely not depend too much on that feature. I know maintainers in this project want to remove it, and I know the Docker Hub team also wants to sunset the feature (see https://github.com/docker/roadmap/issues/173 - probably other tickets as well). That would mean that v1 images could still be accessible, but only _actual_ v1 images, but no conversion anymore.

**Comment by milosgajdos** [comment]
@xAt0mZ mind closing this issue now?

**Comment by xAt0mZ** [comment]
I validated with the following script that getting the digest doesn't mutate the filesystem.
Everything looks good.

Thanks a lot for your help and indications! :raised_hands: 

**SCRIPT**
```sh
#!/bin/bash

CONTAINER_NAME="registry2"
TEMP_IMAGE="registry-temp"
REGISTRY_URL="localhost:5001"
SOURCE_IMAGE="hello-world:latest"
IMAGE="myimage"
TAG="latest"

echo ">>>>> Create registry container"
docker run -d \
  --name $CONTAINER_NAME \
  -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry2 \
  -p 5001:5000 \
  registry:2

echo ">>>>> Pull image"
docker pull $SOURCE_IMAGE

echo ">>>>> Tag image"
docker tag $SOURCE_IMAGE $REGISTRY_URL/$IMAGE:$TAG

echo ">>>>> Push image"
docker push $REGISTRY_URL/$IMAGE:$TAG

echo ">>>>> Commit container"
docker commit $CONTAINER_NAME $TEMP_IMAGE

echo ">>>>> Remove registry container"
docker rm -fv $CONTAINER_NAME

echo ">>>>> Create registry container from commit"
docker run -d \
  --name $CONTAINER_NAME \
  -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry2 \
  -p 5001:5000 \
  $TEMP_IMAGE

DIGEST=$(
  curl -s -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
    "$REGISTRY_URL/v2/$IMAGE/manifests/$TAG" |
    jq --raw-output .config.digest
)

echo ">>>>> CURL image config"
curl -s "$REGISTRY_URL/v2/$IMAGE/blobs/$DIGEST" | jq .

echo ">>>>> DIFF registry container"
docker diff $CONTAINER_NAME

echo ">>>>> Remove registry container from commit"
docker rm -fv $CONTAINER_NAME
```


**OUTPUT**
```
>>>>> Create registry container
f9f36ef8e496c6cce0dfa4c66efa2e0f6811ce767ef789134d338ebd090bed20
>>>>> Pull image
latest: Pulling from library/hello-world
Digest: sha256:53cc4d415d839c98be39331c948609b659ed725170ad2ca8eb36951288f81b75
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest
>>>>> Tag image
>>>>> Push image
The push refers to repository [localhost:5001/myimage]
ac28800ec8bb: Pushed 
latest: digest: sha256:d37ada95d47ad12224c205a938129df7a3e52345828b4fa27b03a98825d1e2e7 size: 524
>>>>> Commit container
sha256:d9bc0d7e61344ed59574758a263a7b2d393e1cfaac183bcfb6d361ec3582258f
>>>>> Remove registry container
registry2
>>>>> Create registry container from commit
7522cba5a8b656274e8a45fc87029b324ba40c96f723f18cd67486a86634901b
>>>>> CURL image config
{
  "architecture": "amd64",
  "config": {
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ],
    "Cmd": [
      "/hello"
    ],
    "WorkingDir": "/",
    "ArgsEscaped": true,
    "OnBuild": null
  },
  "created": "2023-05-02T16:49:27Z",
  "history": [
    {
      "created": "2023-05-02T16:49:27Z",
      "created_by": "COPY hello / # buildkit",
      "comment": "buildkit.dockerfile.v0"
    },
    {
      "created": "2023-05-02T16:49:27Z",
      "created_by": "CMD [\"/hello\"]",
      "comment": "buildkit.dockerfile.v0",
      "empty_layer": true
    }
  ],
  "os": "linux",
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:ac28800ec8bb38d5c35b49d45a6ac4777544941199075dff8c4eb63e093aa81e"
    ]
  }
}
>>>>> DIFF registry container
>>>>> Remove registry container from commit
registry2

```
