### ISSUE TITLE
Add more Documentation around the plugable Auth

### ISSUE THREAD

**Issue by schmitch** [distribution/distribution#535]
It would be great if we could have more information about Auth in general and about the plugable Auth.
So people could easily add basic auth or another auth model

**Comment by AngryHacker** [comment]
I strongly approve that.
Now I don't know how to use the auth option in the document.

**Comment by stevvooe** [comment]
@schmitch The best documentation is the [godoc for the auth package](http://godoc.org/github.com/docker/distribution/registry/auth). There is an example and quite a bit of detail on how to implement a new access controller. The documentation for configuring authentication is [here](https://github.com/docker/distribution/blob/master/docs/configuration.md#auth). It would be good to know what you believe is missing or submit a PR with some additions.

For an example of adding an authentication provider, please see #409. It hasn't yet been merged since it is missing important functionality, so perhaps you could pick it up.

**Comment by milosgajdos** [comment]
Closing as wildly outdated. Feel free to reopen if you think the current official docs are not sufficient.
