### ISSUE TITLE
Catalog API is not usable with a large number of repositories backed by S3

### ISSUE THREAD

**Issue by aaronlehmann** [distribution/distribution#947]
The catalog API works by recursively listing files in the backend storage. This is a sequential process that can take a long time if the backend storage is a network service such as S3. The S3 case is particularly bad because each request involves a TCP connection and SSL handshake, which add more latency than a simple TCP round-trip.

The filter passed to `Walk` avoids recursing all the way into repository subdirectories, but there's still a `Stat` done for each subdirectory of a repository (`_layers`, `_manifests`, and `_uploads`). This means there are about 5 new SSL connections per repository. Multiply this by the number of repositories (since there's no concurrency in the `Walk` function), and this becomes completely impractical for any large-scale registry.

There are a few minor things we could do to significantly improve performance here. We could avoid statting `_layers`, `_manifests`, and `_uploads`, because this is not really necessary for listing repositories. It would also help to add some concurrency to `Walk`, since currently it must wait for `a/foo` to be statted and listed before `a/bar` can be statted and listed (and so on).

In the longer term, it would be nice to use a S3 library that uses a connection pool instead of constantly opening new connections, and using a database or redis cache might be preferable to walking the backend storage every time the catalog API is used.

**Comment by stevvooe** [comment]
This reads like another "s3 is slow" bug, but these `Stat` calls are necessary to identify whether or not a given path is a repository.

Breaking this down, let's save we have 1 million repositories with 64 byte names. This is only 64MB of data. Another option here would be to have a `Find` command on the storage driver interface that emits all of the directories under a specific path. This would eliminate the round trip and make the call limited by bandwidth and s3 response time.

Either way, this was a known limitation when adding the requested catalog API.

**Comment by baldzern4** [comment]
Hi @aaronlehmann @stevvooe ,
we also see this behaviour on our private registry using s3 as backend.
The call to the catalog API (/v2/_catalog) takes currently 30 seconds for 35 images. Thats way too much.   

So I would second any improvements on this issue.

Br,
Jörg

**Comment by stevvooe** [comment]
@baldzern4 That is very surprising to see this issue with only 35 repositories. This should only be a problem for backends with a large number of repositories. Are they heavily nested?

**Comment by baldzern4** [comment]
@stevvooe We are creating new containers via our CI environment. Each image has currently around 100 tags, because we create 2-3 new images a day.

**Comment by stevvooe** [comment]
@baldzern4 The number of tags shouldn't affect the response time. This should be repository bound. Do your repository names have a large number of path components? A repository name like "a/b/c/d" would be more expensive to walk than "a/b", due to the limitations of the driver interface.

The other aspect you may want to look at is pure s3 latency. Coupled with a large number of path components, s3 latency can make this call very slow.

**Comment by benbarclay** [comment]
I see this issue on a registry with ~400 repositories stored in S3 in the same region. Each request to the catalog endpoint takes ~2.5 mins.

Is there a reason that this is not cached? I don't mind the walk being expensive if the results can be cached for further requests.

**Comment by stevvooe** [comment]
@benbarclay This is not currently cached because we have avoided the complexity. This is an administration call and typically not used in performance critical applications. Caching should be straightforward and the data might already be there from the blob descriptor cache.

Part of this issue is that s3 is just too darn slow. I think the addition of a `Walk` or `Find` command to the storagedriver API would also provide a substantial speedup without the need for introducing caching.

Have you analyzed the request trace for a particular catalog request? It is also possible that we are walking too "deeply", creating extra requests.

**Comment by m-masataka** [comment]
@stevvooe Thank you for guide me from issue #1963 .
I have one more question.
I can't understand the "complexity" of cache or metadata. It means it's difficult to sync metadata and storage? Or we should implement metadata in the other product (such as docker-notary), if we need it?
I would be glad if you teach me.

**Comment by milosgajdos** [comment]
This issue should be alleviated with https://github.com/distribution/distribution/pull/3685 available in the last release.

**Comment by milosgajdos** [comment]
Closing, hopefully addressed by https://github.com/distribution/distribution/pull/3685

Feel free to reopen.
